export const CITY_ZONE_OPTIONS: Record<string, string[]> = {
  Bogota: [
    'Usaquen',
    'Chapinero',
    'Santa Fe',
    'San Cristobal',
    'Usme',
    'Tunjuelito',
    'Bosa',
    'Kennedy',
    'Fontibon',
    'Engativa',
    'Suba',
    'Barrios Unidos',
    'Teusaquillo',
    'Los Martires',
    'Antonio Narino',
    'Puente Aranda',
    'La Candelaria',
    'Rafael Uribe Uribe',
    'Ciudad Bolivar',
    'Norte',
    'Centro',
    'Occidente',
    'Sur',
  ],
  Medellin: [
    'El Poblado',
    'Laureles',
    'Belen',
    'Envigado',
    'Sabaneta',
    'Centro',
    'Guayabal',
    'Robledo',
    'Buenos Aires',
    'Castilla',
    'Aranjuez',
    'Itagui',
  ],
  Cali: [
    'Norte',
    'Sur',
    'Oeste',
    'Centro',
    'Jamundi',
    'Ciudad Jardin',
    'San Fernando',
    'Granada',
    'Valle del Lili',
    'Caney',
    'Pasoancho',
    'Aguablanca',
  ],
  Barranquilla: [
    'Norte',
    'Centro',
    'Riomar',
    'Soledad',
    'Alto Prado',
    'Buenavista',
    'Villa Carolina',
    'Boston',
    'Ciudad Jardin',
    'Metropolitana',
  ],
  Cartagena: [
    'Bocagrande',
    'Centro',
    'Manga',
    'Zona Norte',
    'Crespo',
    'Marbella',
    'La Boquilla',
    'Castillogrande',
    'Pie de la Popa',
    'El Laguito',
  ],
  Bucaramanga: [
    'Cabecera',
    'Centro',
    'Cacique',
    'Floridablanca',
    'Canaveral',
    'Real de Minas',
    'Sotomayor',
    'San Alonso',
    'Provenza',
    'Girardot',
  ],
  Pereira: ['Circunvalar', 'Centro', 'Dosquebradas', 'Cerritos', 'Pinares'],
  Manizales: ['Palermo', 'Cable', 'Centro', 'Milan', 'Chipre'],
  Cucuta: ['Caobos', 'Centro', 'La Riviera', 'Guaimaral', 'Colsag'],
  SantaMarta: ['Rodadero', 'Centro', 'Bello Horizonte', 'Mamatoco', 'Pozos Colorados'],
  Ibague: ['Centro', 'El Salado', 'La Samaria', 'Mirolindo', 'Picaleña'],
  Villavicencio: ['Centro', 'Buque', 'Barzal', 'La Esperanza', 'Caudal'],
  Neiva: ['Centro', 'Canaima', 'Santa Ines', 'Tierra Linda', 'Sur'],
  Monteria: ['Centro', 'La Castellana', 'Monteverde', 'Buenavista', 'Norte'],
  Pasto: ['Centro', 'Unicentro', 'La Aurora', 'Maridiaz', 'Anganoy'],
  Armenia: ['Centro', 'Norte', 'Quimbaya', 'La Castellana', 'Portal del Quindio'],
}

export const CONTACT_MODE_OPTIONS = [
  {
    value: 'lead_form' as const,
    label: 'Contacto web',
    objective: 'Clientes potenciales',
  },
  {
    value: 'whatsapp' as const,
    label: 'Contactarme por WhatsApp',
    objective: 'Mensajes / WhatsApp',
  },
]
